"""Generate src/syms.h: fixed addresses of the engine symbols we use (OLGame.x86_64 is non-PIE)."""
import sys,os
sys.path.insert(0,os.path.dirname(__file__))
from elfvt import addr
WANT={
 'GEngine':'GEngine','GNames':'FName::Names','GObjects':'UObject::GObjObjects',
 'VT_UOLEngine':'vtable for UOLEngine','UOLEngine_Tick':'UOLEngine::Tick(float)',
 'StaticConstructObject':'UObject::StaticConstructObject(UClass*, UObject*, FName, unsigned long, UObject*, FOutputDevice*, UObject*, FObjectInstancingGraph*)',
 'AddToRoot':'UObject::AddToRoot()','RemoveFromRoot':'UObject::RemoveFromRoot()','GetTransientPackage':'UObject::GetTransientPackage()',
 'appRealloc':'appRealloc(void*, unsigned int, unsigned int)','FlushRenderingCommands':'FlushRenderingCommands()',
 'SM_ReleaseResources':'UStaticMesh::ReleaseResources()','SM_InitResources':'UStaticMesh::InitResources()',
 'SMVB_Init':'FStaticMeshVertexBuffer::Init(TArray<FStaticMeshBuildVertex, FDefaultAllocator> const&, unsigned int)',
 'PosVB_Init':'FPositionVertexBuffer::Init(TArray<FStaticMeshBuildVertex, FDefaultAllocator> const&)',
 'BulkLock':'FUntypedBulkData::Lock(unsigned int)','BulkUnlock':'FUntypedBulkData::Unlock()','BulkRealloc':'FUntypedBulkData::Realloc(int)',
 'Tex2D_UpdateResource':'UTexture2D::UpdateResource()',
}
out=['// generated by tools/gensyms.py from OLGame.x86_64 (Steam build 576074)','#pragma once']
for k,v in WANT.items(): out.append(f'#define A_{k} 0x{addr[v]:x}ULL')
open(os.path.join(os.path.dirname(__file__),'../src/syms.h'),'w').write('\n'.join(out)+'\n')
print('\n'.join(out))
