// generated by tools/gensyms.py from OLGame.x86_64 (Steam build 576074)
#pragma once
#define A_GEngine 0x4121bd0ULL
#define A_GNames 0x42331a0ULL
#define A_GObjects 0x42b8e80ULL
#define A_VT_UOLEngine 0x32dfbc0ULL
#define A_UOLEngine_Tick 0xfd0550ULL
#define A_StaticConstructObject 0x265e8b0ULL
#define A_AddToRoot 0x264cce0ULL
#define A_GetTransientPackage 0x264ccc0ULL
#define A_appRealloc 0x26212e0ULL
#define A_FlushRenderingCommands 0x1a10380ULL
#define A_SM_ReleaseResources 0x23b1310ULL
#define A_SM_InitResources 0x23b1170ULL
#define A_SMVB_Init 0x23af780ULL
#define A_PosVB_Init 0x23b2710ULL
#define A_BulkLock 0x25a9170ULL
#define A_BulkUnlock 0x25a81b0ULL
#define A_BulkRealloc 0x25a8200ULL
#define A_Tex2D_UpdateResource 0x1b1ab40ULL
